//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.296.
// 
#pragma warning disable 1591

namespace NWN2_ServerMonitor.com.valhallalegends.mst.api1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_INWNMasterServerAPI", Namespace="http://tempuri.org/")]
    public partial class NWNMasterServerAPI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LookupServerByNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback LookupServerByAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOnlineServerListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOnlineUserCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSupportedProductListOperationCompleted;
        
        private System.Threading.SendOrPostCallback LookupServerByModuleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NWNMasterServerAPI() {
            this.Url = "http://api.mst.valhallalegends.com/NWNMasterServerAPI/NWNMasterServerAPI.svc/ASMX" +
                "";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LookupServerByNameCompletedEventHandler LookupServerByNameCompleted;
        
        /// <remarks/>
        public event LookupServerByAddressCompletedEventHandler LookupServerByAddressCompleted;
        
        /// <remarks/>
        public event GetOnlineServerListCompletedEventHandler GetOnlineServerListCompleted;
        
        /// <remarks/>
        public event GetOnlineUserCountCompletedEventHandler GetOnlineUserCountCompleted;
        
        /// <remarks/>
        public event GetSupportedProductListCompletedEventHandler GetSupportedProductListCompleted;
        
        /// <remarks/>
        public event LookupServerByModuleCompletedEventHandler LookupServerByModuleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.mst.valhallalegends.com/NWNMasterServerAPI/INWNMasterServerAPI/LookupS" +
            "erverByName", RequestNamespace="http://api.mst.valhallalegends.com/NWNMasterServerAPI", ResponseNamespace="http://api.mst.valhallalegends.com/NWNMasterServerAPI", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/NWN")]
        public NWGameServer[] LookupServerByName([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Product, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ServerName) {
            object[] results = this.Invoke("LookupServerByName", new object[] {
                        Product,
                        ServerName});
            return ((NWGameServer[])(results[0]));
        }
        
        /// <remarks/>
        public void LookupServerByNameAsync(string Product, string ServerName) {
            this.LookupServerByNameAsync(Product, ServerName, null);
        }
        
        /// <remarks/>
        public void LookupServerByNameAsync(string Product, string ServerName, object userState) {
            if ((this.LookupServerByNameOperationCompleted == null)) {
                this.LookupServerByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLookupServerByNameOperationCompleted);
            }
            this.InvokeAsync("LookupServerByName", new object[] {
                        Product,
                        ServerName}, this.LookupServerByNameOperationCompleted, userState);
        }
        
        private void OnLookupServerByNameOperationCompleted(object arg) {
            if ((this.LookupServerByNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LookupServerByNameCompleted(this, new LookupServerByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.mst.valhallalegends.com/NWNMasterServerAPI/INWNMasterServerAPI/LookupS" +
            "erverByAddress", RequestNamespace="http://api.mst.valhallalegends.com/NWNMasterServerAPI", ResponseNamespace="http://api.mst.valhallalegends.com/NWNMasterServerAPI", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NWGameServer LookupServerByAddress([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Product, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ServerAddress) {
            object[] results = this.Invoke("LookupServerByAddress", new object[] {
                        Product,
                        ServerAddress});
            return ((NWGameServer)(results[0]));
        }
        
        /// <remarks/>
        public void LookupServerByAddressAsync(string Product, string ServerAddress) {
            this.LookupServerByAddressAsync(Product, ServerAddress, null);
        }
        
        /// <remarks/>
        public void LookupServerByAddressAsync(string Product, string ServerAddress, object userState) {
            if ((this.LookupServerByAddressOperationCompleted == null)) {
                this.LookupServerByAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLookupServerByAddressOperationCompleted);
            }
            this.InvokeAsync("LookupServerByAddress", new object[] {
                        Product,
                        ServerAddress}, this.LookupServerByAddressOperationCompleted, userState);
        }
        
        private void OnLookupServerByAddressOperationCompleted(object arg) {
            if ((this.LookupServerByAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LookupServerByAddressCompleted(this, new LookupServerByAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.mst.valhallalegends.com/NWNMasterServerAPI/INWNMasterServerAPI/GetOnli" +
            "neServerList", RequestNamespace="http://api.mst.valhallalegends.com/NWNMasterServerAPI", ResponseNamespace="http://api.mst.valhallalegends.com/NWNMasterServerAPI", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/NWN")]
        public NWGameServer[] GetOnlineServerList([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Product) {
            object[] results = this.Invoke("GetOnlineServerList", new object[] {
                        Product});
            return ((NWGameServer[])(results[0]));
        }
        
        /// <remarks/>
        public void GetOnlineServerListAsync(string Product) {
            this.GetOnlineServerListAsync(Product, null);
        }
        
        /// <remarks/>
        public void GetOnlineServerListAsync(string Product, object userState) {
            if ((this.GetOnlineServerListOperationCompleted == null)) {
                this.GetOnlineServerListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOnlineServerListOperationCompleted);
            }
            this.InvokeAsync("GetOnlineServerList", new object[] {
                        Product}, this.GetOnlineServerListOperationCompleted, userState);
        }
        
        private void OnGetOnlineServerListOperationCompleted(object arg) {
            if ((this.GetOnlineServerListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOnlineServerListCompleted(this, new GetOnlineServerListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.mst.valhallalegends.com/NWNMasterServerAPI/INWNMasterServerAPI/GetOnli" +
            "neUserCount", RequestNamespace="http://api.mst.valhallalegends.com/NWNMasterServerAPI", ResponseNamespace="http://api.mst.valhallalegends.com/NWNMasterServerAPI", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetOnlineUserCount([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Product, out uint GetOnlineUserCountResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool GetOnlineUserCountResultSpecified) {
            object[] results = this.Invoke("GetOnlineUserCount", new object[] {
                        Product});
            GetOnlineUserCountResult = ((uint)(results[0]));
            GetOnlineUserCountResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void GetOnlineUserCountAsync(string Product) {
            this.GetOnlineUserCountAsync(Product, null);
        }
        
        /// <remarks/>
        public void GetOnlineUserCountAsync(string Product, object userState) {
            if ((this.GetOnlineUserCountOperationCompleted == null)) {
                this.GetOnlineUserCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOnlineUserCountOperationCompleted);
            }
            this.InvokeAsync("GetOnlineUserCount", new object[] {
                        Product}, this.GetOnlineUserCountOperationCompleted, userState);
        }
        
        private void OnGetOnlineUserCountOperationCompleted(object arg) {
            if ((this.GetOnlineUserCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOnlineUserCountCompleted(this, new GetOnlineUserCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.mst.valhallalegends.com/NWNMasterServerAPI/INWNMasterServerAPI/GetSupp" +
            "ortedProductList", RequestNamespace="http://api.mst.valhallalegends.com/NWNMasterServerAPI", ResponseNamespace="http://api.mst.valhallalegends.com/NWNMasterServerAPI", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] GetSupportedProductList() {
            object[] results = this.Invoke("GetSupportedProductList", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSupportedProductListAsync() {
            this.GetSupportedProductListAsync(null);
        }
        
        /// <remarks/>
        public void GetSupportedProductListAsync(object userState) {
            if ((this.GetSupportedProductListOperationCompleted == null)) {
                this.GetSupportedProductListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSupportedProductListOperationCompleted);
            }
            this.InvokeAsync("GetSupportedProductList", new object[0], this.GetSupportedProductListOperationCompleted, userState);
        }
        
        private void OnGetSupportedProductListOperationCompleted(object arg) {
            if ((this.GetSupportedProductListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSupportedProductListCompleted(this, new GetSupportedProductListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.mst.valhallalegends.com/NWNMasterServerAPI/INWNMasterServerAPI/LookupS" +
            "erverByModule", RequestNamespace="http://api.mst.valhallalegends.com/NWNMasterServerAPI", ResponseNamespace="http://api.mst.valhallalegends.com/NWNMasterServerAPI", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/NWN")]
        public NWGameServer[] LookupServerByModule([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Product, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Module) {
            object[] results = this.Invoke("LookupServerByModule", new object[] {
                        Product,
                        Module});
            return ((NWGameServer[])(results[0]));
        }
        
        /// <remarks/>
        public void LookupServerByModuleAsync(string Product, string Module) {
            this.LookupServerByModuleAsync(Product, Module, null);
        }
        
        /// <remarks/>
        public void LookupServerByModuleAsync(string Product, string Module, object userState) {
            if ((this.LookupServerByModuleOperationCompleted == null)) {
                this.LookupServerByModuleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLookupServerByModuleOperationCompleted);
            }
            this.InvokeAsync("LookupServerByModule", new object[] {
                        Product,
                        Module}, this.LookupServerByModuleOperationCompleted, userState);
        }
        
        private void OnLookupServerByModuleOperationCompleted(object arg) {
            if ((this.LookupServerByModuleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LookupServerByModuleCompleted(this, new LookupServerByModuleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NWN")]
    public partial class NWGameServer {
        
        private uint activePlayerCountField;
        
        private bool activePlayerCountFieldSpecified;
        
        private uint buildNumberField;
        
        private bool buildNumberFieldSpecified;
        
        private bool eLCEnforcedField;
        
        private bool eLCEnforcedFieldSpecified;
        
        private uint expansionsMaskField;
        
        private bool expansionsMaskFieldSpecified;
        
        private uint gameTypeField;
        
        private bool gameTypeFieldSpecified;
        
        private bool iLREnforcedField;
        
        private bool iLREnforcedFieldSpecified;
        
        private System.DateTime lastHeartbeatField;
        
        private bool lastHeartbeatFieldSpecified;
        
        private bool localVaultField;
        
        private bool localVaultFieldSpecified;
        
        private uint maximumLevelField;
        
        private bool maximumLevelFieldSpecified;
        
        private uint maximumPlayerCountField;
        
        private bool maximumPlayerCountFieldSpecified;
        
        private uint minimumLevelField;
        
        private bool minimumLevelFieldSpecified;
        
        private string moduleDescriptionField;
        
        private string moduleNameField;
        
        private string moduleUrlField;
        
        private bool onePartyOnlyField;
        
        private bool onePartyOnlyFieldSpecified;
        
        private bool onlineField;
        
        private bool onlineFieldSpecified;
        
        private uint pVPLevelField;
        
        private bool pVPLevelFieldSpecified;
        
        private string pWCUrlField;
        
        private bool playerPauseField;
        
        private bool playerPauseFieldSpecified;
        
        private bool privateServerField;
        
        private bool privateServerFieldSpecified;
        
        private string productField;
        
        private string serverAddressField;
        
        private string serverNameField;
        
        /// <remarks/>
        public uint ActivePlayerCount {
            get {
                return this.activePlayerCountField;
            }
            set {
                this.activePlayerCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActivePlayerCountSpecified {
            get {
                return this.activePlayerCountFieldSpecified;
            }
            set {
                this.activePlayerCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint BuildNumber {
            get {
                return this.buildNumberField;
            }
            set {
                this.buildNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BuildNumberSpecified {
            get {
                return this.buildNumberFieldSpecified;
            }
            set {
                this.buildNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool ELCEnforced {
            get {
                return this.eLCEnforcedField;
            }
            set {
                this.eLCEnforcedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ELCEnforcedSpecified {
            get {
                return this.eLCEnforcedFieldSpecified;
            }
            set {
                this.eLCEnforcedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint ExpansionsMask {
            get {
                return this.expansionsMaskField;
            }
            set {
                this.expansionsMaskField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpansionsMaskSpecified {
            get {
                return this.expansionsMaskFieldSpecified;
            }
            set {
                this.expansionsMaskFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint GameType {
            get {
                return this.gameTypeField;
            }
            set {
                this.gameTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GameTypeSpecified {
            get {
                return this.gameTypeFieldSpecified;
            }
            set {
                this.gameTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool ILREnforced {
            get {
                return this.iLREnforcedField;
            }
            set {
                this.iLREnforcedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ILREnforcedSpecified {
            get {
                return this.iLREnforcedFieldSpecified;
            }
            set {
                this.iLREnforcedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastHeartbeat {
            get {
                return this.lastHeartbeatField;
            }
            set {
                this.lastHeartbeatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastHeartbeatSpecified {
            get {
                return this.lastHeartbeatFieldSpecified;
            }
            set {
                this.lastHeartbeatFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool LocalVault {
            get {
                return this.localVaultField;
            }
            set {
                this.localVaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LocalVaultSpecified {
            get {
                return this.localVaultFieldSpecified;
            }
            set {
                this.localVaultFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint MaximumLevel {
            get {
                return this.maximumLevelField;
            }
            set {
                this.maximumLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaximumLevelSpecified {
            get {
                return this.maximumLevelFieldSpecified;
            }
            set {
                this.maximumLevelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint MaximumPlayerCount {
            get {
                return this.maximumPlayerCountField;
            }
            set {
                this.maximumPlayerCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaximumPlayerCountSpecified {
            get {
                return this.maximumPlayerCountFieldSpecified;
            }
            set {
                this.maximumPlayerCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint MinimumLevel {
            get {
                return this.minimumLevelField;
            }
            set {
                this.minimumLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinimumLevelSpecified {
            get {
                return this.minimumLevelFieldSpecified;
            }
            set {
                this.minimumLevelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ModuleDescription {
            get {
                return this.moduleDescriptionField;
            }
            set {
                this.moduleDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ModuleName {
            get {
                return this.moduleNameField;
            }
            set {
                this.moduleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ModuleUrl {
            get {
                return this.moduleUrlField;
            }
            set {
                this.moduleUrlField = value;
            }
        }
        
        /// <remarks/>
        public bool OnePartyOnly {
            get {
                return this.onePartyOnlyField;
            }
            set {
                this.onePartyOnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OnePartyOnlySpecified {
            get {
                return this.onePartyOnlyFieldSpecified;
            }
            set {
                this.onePartyOnlyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Online {
            get {
                return this.onlineField;
            }
            set {
                this.onlineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OnlineSpecified {
            get {
                return this.onlineFieldSpecified;
            }
            set {
                this.onlineFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint PVPLevel {
            get {
                return this.pVPLevelField;
            }
            set {
                this.pVPLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PVPLevelSpecified {
            get {
                return this.pVPLevelFieldSpecified;
            }
            set {
                this.pVPLevelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PWCUrl {
            get {
                return this.pWCUrlField;
            }
            set {
                this.pWCUrlField = value;
            }
        }
        
        /// <remarks/>
        public bool PlayerPause {
            get {
                return this.playerPauseField;
            }
            set {
                this.playerPauseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PlayerPauseSpecified {
            get {
                return this.playerPauseFieldSpecified;
            }
            set {
                this.playerPauseFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool PrivateServer {
            get {
                return this.privateServerField;
            }
            set {
                this.privateServerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrivateServerSpecified {
            get {
                return this.privateServerFieldSpecified;
            }
            set {
                this.privateServerFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ServerAddress {
            get {
                return this.serverAddressField;
            }
            set {
                this.serverAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ServerName {
            get {
                return this.serverNameField;
            }
            set {
                this.serverNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LookupServerByNameCompletedEventHandler(object sender, LookupServerByNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LookupServerByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LookupServerByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NWGameServer[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NWGameServer[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LookupServerByAddressCompletedEventHandler(object sender, LookupServerByAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LookupServerByAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LookupServerByAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NWGameServer Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NWGameServer)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetOnlineServerListCompletedEventHandler(object sender, GetOnlineServerListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOnlineServerListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOnlineServerListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NWGameServer[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NWGameServer[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetOnlineUserCountCompletedEventHandler(object sender, GetOnlineUserCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOnlineUserCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOnlineUserCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public uint GetOnlineUserCountResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((uint)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool GetOnlineUserCountResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetSupportedProductListCompletedEventHandler(object sender, GetSupportedProductListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSupportedProductListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSupportedProductListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LookupServerByModuleCompletedEventHandler(object sender, LookupServerByModuleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LookupServerByModuleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LookupServerByModuleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NWGameServer[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NWGameServer[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591