//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NWGameServer", Namespace="http://schemas.datacontract.org/2004/07/NWN")]
    [System.SerializableAttribute()]
    public partial class NWGameServer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint ActivePlayerCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint BuildNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint ExpansionsMaskField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastHeartbeatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LocalVaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint MaximumPlayerCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PrivateServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServerAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServerNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint ActivePlayerCount {
            get {
                return this.ActivePlayerCountField;
            }
            set {
                if ((this.ActivePlayerCountField.Equals(value) != true)) {
                    this.ActivePlayerCountField = value;
                    this.RaisePropertyChanged("ActivePlayerCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint BuildNumber {
            get {
                return this.BuildNumberField;
            }
            set {
                if ((this.BuildNumberField.Equals(value) != true)) {
                    this.BuildNumberField = value;
                    this.RaisePropertyChanged("BuildNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint ExpansionsMask {
            get {
                return this.ExpansionsMaskField;
            }
            set {
                if ((this.ExpansionsMaskField.Equals(value) != true)) {
                    this.ExpansionsMaskField = value;
                    this.RaisePropertyChanged("ExpansionsMask");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastHeartbeat {
            get {
                return this.LastHeartbeatField;
            }
            set {
                if ((this.LastHeartbeatField.Equals(value) != true)) {
                    this.LastHeartbeatField = value;
                    this.RaisePropertyChanged("LastHeartbeat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LocalVault {
            get {
                return this.LocalVaultField;
            }
            set {
                if ((this.LocalVaultField.Equals(value) != true)) {
                    this.LocalVaultField = value;
                    this.RaisePropertyChanged("LocalVault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint MaximumPlayerCount {
            get {
                return this.MaximumPlayerCountField;
            }
            set {
                if ((this.MaximumPlayerCountField.Equals(value) != true)) {
                    this.MaximumPlayerCountField = value;
                    this.RaisePropertyChanged("MaximumPlayerCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleName {
            get {
                return this.ModuleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuleNameField, value) != true)) {
                    this.ModuleNameField = value;
                    this.RaisePropertyChanged("ModuleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Online {
            get {
                return this.OnlineField;
            }
            set {
                if ((this.OnlineField.Equals(value) != true)) {
                    this.OnlineField = value;
                    this.RaisePropertyChanged("Online");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PrivateServer {
            get {
                return this.PrivateServerField;
            }
            set {
                if ((this.PrivateServerField.Equals(value) != true)) {
                    this.PrivateServerField = value;
                    this.RaisePropertyChanged("PrivateServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServerAddress {
            get {
                return this.ServerAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerAddressField, value) != true)) {
                    this.ServerAddressField = value;
                    this.RaisePropertyChanged("ServerAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServerName {
            get {
                return this.ServerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerNameField, value) != true)) {
                    this.ServerNameField = value;
                    this.RaisePropertyChanged("ServerName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.mst.valhallalegends.com/NWNMasterServerAPI", ConfigurationName="ServiceReference1.INWNMasterServerAPI")]
    public interface INWNMasterServerAPI {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.mst.valhallalegends.com/NWNMasterServerAPI/INWNMasterServerAPI/LookupS" +
            "erverByName", ReplyAction="http://api.mst.valhallalegends.com/NWNMasterServerAPI/INWNMasterServerAPI/LookupS" +
            "erverByNameResponse")]
        ConsoleApplication1.ServiceReference1.NWGameServer[] LookupServerByName(string Product, string ServerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.mst.valhallalegends.com/NWNMasterServerAPI/INWNMasterServerAPI/LookupS" +
            "erverByAddress", ReplyAction="http://api.mst.valhallalegends.com/NWNMasterServerAPI/INWNMasterServerAPI/LookupS" +
            "erverByAddressResponse")]
        ConsoleApplication1.ServiceReference1.NWGameServer LookupServerByAddress(string Product, string ServerAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.mst.valhallalegends.com/NWNMasterServerAPI/INWNMasterServerAPI/GetOnli" +
            "neServerList", ReplyAction="http://api.mst.valhallalegends.com/NWNMasterServerAPI/INWNMasterServerAPI/GetOnli" +
            "neServerListResponse")]
        ConsoleApplication1.ServiceReference1.NWGameServer[] GetOnlineServerList(string Product);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INWNMasterServerAPIChannel : ConsoleApplication1.ServiceReference1.INWNMasterServerAPI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NWNMasterServerAPIClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference1.INWNMasterServerAPI>, ConsoleApplication1.ServiceReference1.INWNMasterServerAPI {
        
        public NWNMasterServerAPIClient() {
        }
        
        public NWNMasterServerAPIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NWNMasterServerAPIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NWNMasterServerAPIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NWNMasterServerAPIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleApplication1.ServiceReference1.NWGameServer[] LookupServerByName(string Product, string ServerName) {
            return base.Channel.LookupServerByName(Product, ServerName);
        }
        
        public ConsoleApplication1.ServiceReference1.NWGameServer LookupServerByAddress(string Product, string ServerAddress) {
            return base.Channel.LookupServerByAddress(Product, ServerAddress);
        }
        
        public ConsoleApplication1.ServiceReference1.NWGameServer[] GetOnlineServerList(string Product) {
            return base.Channel.GetOnlineServerList(Product);
        }
    }
}
